baseURL = "https://sjsp.netlify.app/"
title = "St Joseph's Roman Catholic Church Ansdell"
languageCode = "en-us"
theme = "ananke"

[module]
# optional: set hugoVersion, etc.


[params]
text_color = "mid-gray"
author = ""
favicon = ""
# site_logo = "https://st-josephsansdell.net/wp-content/uploads/2015/06/St-Josephs-New-Circle-Logo-HD-Colour1.png"
# description = "SJSP_Description_Change_In_Params."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-washed-yellow"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-bottom"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-white-40"
custom_css = ["custom.css"]  # Register your custom CSS files here

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Mass Times"
    url = "/mass-times/"
    weight = 2

  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 3

  [[menu.main]]
    name = "Bulletins"
    url = "/Bulletins/"
    weight = 4

  [[menu.main]]
    name = "History"
    url = "/history/"
    weight = 5

  [[menu.main]]
    name = "Find Us"
    url = "/find-us/"
    weight = 6

  [[menu.main]]
    name = "St Josephs Care"
    url = "/st-josephs-care/"
    weight = 7

  [[menu.main]]
    name = "Safeguarding"
    url = "/safeguarding/"
    weight = 8